1) From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
2) Replace missing values in Min.Price and Max.Price columns with their respective mean (check documentation).
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
3) How to get the rows of a dataframe with row sum > 100?
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
4) Create a 4x4 NumPy array filled with random integers between 1 and 100. Then, reshape this array into two separate 2D arrays, where one represents the rows and the other represents the columns. Write a function, preferably using a lambda function, to calculate the sum of each row and each column separately, and return the results as two separate NumPy arrays

In [115]:
# Homework 2
import numpy as np
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.head()

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

In [116]:
# 1
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df[::20][['Manufacturer', 'Model', 'Type']]

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

In [117]:
# 2
df['Min.Price'].fillna(df['Price'], inplace=True)
df['Max.Price'].fillna(df['Price'], inplace=True)

df.head()


C:\Users\TerryLu\AppData\Local\Temp\ipykernel_35860\3298327545.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price'].fillna(df['Price'], inplace=True)
C:\Users\TerryLu\AppData\Local\Temp\ipykernel_35860\3298327545.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

Fo

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize       37.7   37.7       44.6      19.0   
4          BMW     535i  Midsize       30.0   30.0       30.0      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

In [118]:
# 3
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df

0   1   2   3
0   36  26  38  32
1   26  16  35  19
2   37  38  21  36
3   18  30  22  39
4   21  31  38  31
5   24  35  38  33
6   15  14  26  39
7   34  23  16  23
8   39  30  22  18
9   26  25  32  33
10  13  35  32  26
11  29  14  35  13
12  17  37  33  30
13  37  20  24  20
14  24  29  27  32

In [119]:
print(np.sum(df, axis = 1))
target_indices = np.where(np.sum(df, axis = 1) > 100)
print(target_indices)

0     132
1      96
2     132
3     109
4     121
5     130
6      94
7      96
8     109
9     116
10    106
11     91
12    117
13    101
14    112
dtype: int64
(array([ 0,  2,  3,  4,  5,  8,  9, 10, 12, 13, 14], dtype=int64),)


In [120]:
# 4
random_array = np.random.randint(1, 101, size=(4, 4)) # Create an array filled with random values
random_array


array([[87,  5, 71, 73],
       [35, 38, 86, 66],
       [31,  4, 22, 85],
       [62, 93, 45, 66]])

In [121]:
# For rows, use the original array
rows_array = random_array

# For columns, use the transpose of the original array
columns_array = random_array.T

sum_func = lambda x: np.sum(x, axis = 1)


print('Row sum is: ')
print(sum_func(rows_array))
print('Col sum is: ')
print(sum_func(columns_array))



Row sum is: 
[236 225 142 266]
Col sum is: 
[215 140 224 290]


## Practice Questions for numpy
1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.
2. Find common elements between A and B. [Hint : Intersection of two sets]
3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]
4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
```
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```

In [122]:
import numpy as np

In [123]:
# 1
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[4,7,8], [1,3,5]])

vertical = np.vstack((A, B))
horizontal = np.hstack((A, B))

print(vertical)
print(horizontal)

[[1 2 3]
 [4 5 6]
 [4 7 8]
 [1 3 5]]
[[1 2 3 4 7 8]
 [4 5 6 1 3 5]]


In [124]:
# 2
# First do reshape
A_size = A.size
B_size = B.size

A_reshaped = A.reshape((1, A_size))
B_reshaped = B.reshape((1, B_size))

# Loop through
for ele in A_reshaped[0]:
    if(ele in B_reshaped):
        print(ele)

1
3
4
5


In [125]:
# 3
# Extract from 2 to 4 (including)
indices = np.where(A<=4)
temp_answer = A[indices]

new_indices = np.where(temp_answer>=2)
final_answer = temp_answer[new_indices]

print(final_answer)

[2 3 4]


In [126]:
# 4
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

first_filered_indices = np.where(iris_2d[: , 2] > 1.5)
print(first_filered_indices)

final_answer = []

for ele in first_filered_indices[0]:
    if(iris_2d[ele][0] < 5.0):
        final_answer.append(ele)


for ele in final_answer:
    print(ele + 1)

(array([  5,  11,  18,  20,  23,  24,  25,  26,  29,  30,  43,  44,  46,
        50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
       102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
       115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
       128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
       141, 142, 143, 144, 145, 146, 147, 148, 149], dtype=int64),)
12
25
30
31
58
107
